# Generated by Django 4.1.2 on 2022-10-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('library_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.library')),
            ],
        ),
    ]
